import 'package:hive_flutter/hive_flutter.dart';
import 'package:kisan_saathi/core/constants/app_constants.dart';
import 'package:kisan_saathi/shared/models/user_model.dart';
import 'package:kisan_saathi/shared/models/field_model.dart';
import 'package:kisan_saathi/shared/models/crop_model.dart';
import 'package:kisan_saathi/shared/models/alert_model.dart';

class StorageService {
  static StorageService? _instance;
  
  StorageService._();
  
  static StorageService get instance {
    _instance ??= StorageService._();
    return _instance!;
  }

  Future<void> init() async {
    await Hive.initFlutter();
    
    // Register adapters
    // Note: Adapters will be generated by build_runner
    // Hive.registerAdapter(UserModelAdapter());
    // Hive.registerAdapter(FieldModelAdapter());
    // Hive.registerAdapter(CropModelAdapter());
    // Hive.registerAdapter(AlertModelAdapter());
    
    // Open boxes
    await Hive.openBox(AppConstants.userBoxName);
    await Hive.openBox(AppConstants.fieldsBoxName);
    await Hive.openBox(AppConstants.cropsBoxName);
    await Hive.openBox(AppConstants.alertsBoxName);
    await Hive.openBox(AppConstants.settingsBoxName);
  }

  Box getUserBox() => Hive.box(AppConstants.userBoxName);
  Box getFieldsBox() => Hive.box(AppConstants.fieldsBoxName);
  Box getCropsBox() => Hive.box(AppConstants.cropsBoxName);
  Box getAlertsBox() => Hive.box(AppConstants.alertsBoxName);
  Box getSettingsBox() => Hive.box(AppConstants.settingsBoxName);

  Future<void> clearAll() async {
    await getUserBox().clear();
    await getFieldsBox().clear();
    await getCropsBox().clear();
    await getAlertsBox().clear();
    await getSettingsBox().clear();
  }
}
