// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD633tJncf8baxXJ_cev9FzSa-YNDgr2TE',
    appId: '1:241150626109:web:e4c7d58ea3636ce06a9d54',
    messagingSenderId: '241150626109',
    projectId: 'kisansaathi-8dada',
    authDomain: 'kisansaathi-8dada.firebaseapp.com',
    storageBucket: 'kisansaathi-8dada.firebasestorage.app',
    measurementId: 'G-9PY9WBYZDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxceLRAya6q17cZDm4DAytdxqqoy2jZno',
    appId: '1:241150626109:android:1891cce4c2f4a67f6a9d54',
    messagingSenderId: '241150626109',
    projectId: 'kisansaathi-8dada',
    storageBucket: 'kisansaathi-8dada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxceLRAya6q17cZDm4DAytdxqqoy2jZno',
    appId: '1:241150626109:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '241150626109',
    projectId: 'kisansaathi-8dada',
    storageBucket: 'kisansaathi-8dada.firebasestorage.app',
    iosBundleId: 'com.kisansaathi.kisanSaathi',
  );
}
